// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fir,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.882750,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=40,HLS_SYN_LUT=188,HLS_VERSION=2025_1}" *)

module fir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r,
        out_r,
        out_r_ap_vld,
        shift_reg_0_i,
        shift_reg_0_o,
        shift_reg_0_o_ap_vld,
        shift_reg_1_i,
        shift_reg_1_o,
        shift_reg_1_o_ap_vld,
        shift_reg_2_i,
        shift_reg_2_o,
        shift_reg_2_o_ap_vld,
        shift_reg_3_i,
        shift_reg_3_o,
        shift_reg_3_o_ap_vld,
        shift_reg_4_i,
        shift_reg_4_o,
        shift_reg_4_o_ap_vld,
        shift_reg_5_i,
        shift_reg_5_o,
        shift_reg_5_o_ap_vld,
        shift_reg_6_i,
        shift_reg_6_o,
        shift_reg_6_o_ap_vld,
        shift_reg_7_i,
        shift_reg_7_o,
        shift_reg_7_o_ap_vld,
        shift_reg_8_i,
        shift_reg_8_o,
        shift_reg_8_o_ap_vld,
        shift_reg_9_i,
        shift_reg_9_o,
        shift_reg_9_o_ap_vld,
        shift_reg_10_i,
        shift_reg_10_o,
        shift_reg_10_o_ap_vld,
        shift_reg_11_i,
        shift_reg_11_o,
        shift_reg_11_o_ap_vld,
        shift_reg_12_i,
        shift_reg_12_o,
        shift_reg_12_o_ap_vld,
        shift_reg_13_i,
        shift_reg_13_o,
        shift_reg_13_o_ap_vld,
        shift_reg_14_i,
        shift_reg_14_o,
        shift_reg_14_o_ap_vld,
        shift_reg_15,
        shift_reg_15_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_r;
output  [9:0] out_r;
output   out_r_ap_vld;
input  [7:0] shift_reg_0_i;
output  [7:0] shift_reg_0_o;
output   shift_reg_0_o_ap_vld;
input  [7:0] shift_reg_1_i;
output  [7:0] shift_reg_1_o;
output   shift_reg_1_o_ap_vld;
input  [7:0] shift_reg_2_i;
output  [7:0] shift_reg_2_o;
output   shift_reg_2_o_ap_vld;
input  [7:0] shift_reg_3_i;
output  [7:0] shift_reg_3_o;
output   shift_reg_3_o_ap_vld;
input  [7:0] shift_reg_4_i;
output  [7:0] shift_reg_4_o;
output   shift_reg_4_o_ap_vld;
input  [7:0] shift_reg_5_i;
output  [7:0] shift_reg_5_o;
output   shift_reg_5_o_ap_vld;
input  [7:0] shift_reg_6_i;
output  [7:0] shift_reg_6_o;
output   shift_reg_6_o_ap_vld;
input  [7:0] shift_reg_7_i;
output  [7:0] shift_reg_7_o;
output   shift_reg_7_o_ap_vld;
input  [7:0] shift_reg_8_i;
output  [7:0] shift_reg_8_o;
output   shift_reg_8_o_ap_vld;
input  [7:0] shift_reg_9_i;
output  [7:0] shift_reg_9_o;
output   shift_reg_9_o_ap_vld;
input  [7:0] shift_reg_10_i;
output  [7:0] shift_reg_10_o;
output   shift_reg_10_o_ap_vld;
input  [7:0] shift_reg_11_i;
output  [7:0] shift_reg_11_o;
output   shift_reg_11_o_ap_vld;
input  [7:0] shift_reg_12_i;
output  [7:0] shift_reg_12_o;
output   shift_reg_12_o_ap_vld;
input  [7:0] shift_reg_13_i;
output  [7:0] shift_reg_13_o;
output   shift_reg_13_o_ap_vld;
input  [7:0] shift_reg_14_i;
output  [7:0] shift_reg_14_o;
output   shift_reg_14_o_ap_vld;
output  [7:0] shift_reg_15;
output   shift_reg_15_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_r_ap_vld;
reg shift_reg_0_o_ap_vld;
reg shift_reg_1_o_ap_vld;
reg shift_reg_2_o_ap_vld;
reg shift_reg_3_o_ap_vld;
reg shift_reg_4_o_ap_vld;
reg shift_reg_5_o_ap_vld;
reg shift_reg_6_o_ap_vld;
reg shift_reg_7_o_ap_vld;
reg shift_reg_8_o_ap_vld;
reg shift_reg_9_o_ap_vld;
reg shift_reg_10_o_ap_vld;
reg shift_reg_11_o_ap_vld;
reg shift_reg_12_o_ap_vld;
reg shift_reg_13_o_ap_vld;
reg shift_reg_14_o_ap_vld;
reg shift_reg_15_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [7:0] shift_reg_14_read_reg_460;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] tmp9_fu_422_p2;
reg   [9:0] tmp9_reg_465;
wire   [9:0] add_ln23_fu_428_p2;
reg   [9:0] add_ln23_reg_470;
wire   [9:0] add_ln23_3_fu_444_p2;
reg   [9:0] add_ln23_3_reg_475;
wire    ap_block_pp0_stage0_01001;
wire  signed [7:0] sext_ln19_fu_302_p0;
wire    ap_block_pp0_stage0;
wire  signed [7:0] sext_ln23_fu_306_p0;
wire  signed [7:0] sext_ln23_1_fu_310_p0;
wire  signed [7:0] sext_ln23_2_fu_314_p0;
wire  signed [7:0] shift_reg_7_load_cast_fu_318_p0;
wire  signed [7:0] sext_ln23_4_fu_322_p0;
wire  signed [7:0] sext_ln23_3_fu_326_p0;
wire  signed [7:0] shift_reg_13_load_cast_fu_330_p0;
wire  signed [8:0] sext_ln23_fu_306_p1;
wire  signed [8:0] sext_ln23_4_fu_322_p1;
wire   [8:0] tmp_fu_334_p2;
wire  signed [7:0] empty_fu_348_p0;
wire  signed [7:0] empty_fu_348_p1;
wire  signed [8:0] sext_ln23_1_fu_310_p1;
wire  signed [8:0] sext_ln23_3_fu_326_p1;
wire   [8:0] tmp4_fu_354_p2;
wire   [7:0] empty_fu_348_p2;
wire  signed [9:0] tmp4_cast_fu_360_p1;
wire   [9:0] p_shl1_fu_364_p3;
wire   [7:0] tmp61_fu_378_p2;
wire  signed [7:0] empty_4_fu_392_p0;
wire  signed [7:0] empty_4_fu_392_p1;
wire  signed [8:0] sext_ln23_2_fu_314_p1;
wire  signed [8:0] shift_reg_13_load_cast_fu_330_p1;
wire   [8:0] tmp8_fu_398_p2;
wire   [7:0] empty_4_fu_392_p2;
wire   [9:0] p_shl_fu_408_p3;
wire   [9:0] p_neg_fu_416_p2;
wire  signed [9:0] tmp8_cast_fu_404_p1;
wire   [9:0] tmp7_fu_384_p3;
wire   [9:0] tmp5_fu_372_p2;
wire  signed [8:0] shift_reg_7_load_cast_fu_318_p1;
wire  signed [8:0] sext_ln19_fu_302_p1;
wire   [8:0] add_ln23_2_fu_434_p2;
wire  signed [9:0] sext_ln23_5_fu_440_p1;
wire   [9:0] tmp3_fu_340_p3;
wire   [9:0] add_ln23_1_fu_450_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln23_3_reg_475 <= add_ln23_3_fu_444_p2;
        add_ln23_reg_470 <= add_ln23_fu_428_p2;
        shift_reg_14_read_reg_460 <= shift_reg_14_i;
        tmp9_reg_465 <= tmp9_fu_422_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_ap_vld = 1'b1;
    end else begin
        out_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_0_o_ap_vld = 1'b1;
    end else begin
        shift_reg_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_10_o_ap_vld = 1'b1;
    end else begin
        shift_reg_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_11_o_ap_vld = 1'b1;
    end else begin
        shift_reg_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_12_o_ap_vld = 1'b1;
    end else begin
        shift_reg_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_13_o_ap_vld = 1'b1;
    end else begin
        shift_reg_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_14_o_ap_vld = 1'b1;
    end else begin
        shift_reg_14_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_15_ap_vld = 1'b1;
    end else begin
        shift_reg_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_1_o_ap_vld = 1'b1;
    end else begin
        shift_reg_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_2_o_ap_vld = 1'b1;
    end else begin
        shift_reg_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_3_o_ap_vld = 1'b1;
    end else begin
        shift_reg_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_4_o_ap_vld = 1'b1;
    end else begin
        shift_reg_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_5_o_ap_vld = 1'b1;
    end else begin
        shift_reg_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_6_o_ap_vld = 1'b1;
    end else begin
        shift_reg_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_7_o_ap_vld = 1'b1;
    end else begin
        shift_reg_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_8_o_ap_vld = 1'b1;
    end else begin
        shift_reg_8_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shift_reg_9_o_ap_vld = 1'b1;
    end else begin
        shift_reg_9_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln23_1_fu_450_p2 = (add_ln23_reg_470 + tmp9_reg_465);

assign add_ln23_2_fu_434_p2 = ($signed(shift_reg_7_load_cast_fu_318_p1) + $signed(sext_ln19_fu_302_p1));

assign add_ln23_3_fu_444_p2 = ($signed(sext_ln23_5_fu_440_p1) + $signed(tmp3_fu_340_p3));

assign add_ln23_fu_428_p2 = (tmp7_fu_384_p3 + tmp5_fu_372_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign empty_4_fu_392_p0 = shift_reg_5_i;

assign empty_4_fu_392_p1 = shift_reg_13_i;

assign empty_4_fu_392_p2 = ($signed(empty_4_fu_392_p0) + $signed(empty_4_fu_392_p1));

assign empty_fu_348_p0 = shift_reg_2_i;

assign empty_fu_348_p1 = shift_reg_10_i;

assign empty_fu_348_p2 = ($signed(empty_fu_348_p0) + $signed(empty_fu_348_p1));

assign out_r = (add_ln23_3_reg_475 + add_ln23_1_fu_450_p2);

assign p_neg_fu_416_p2 = (10'd0 - p_shl_fu_408_p3);

assign p_shl1_fu_364_p3 = {{empty_fu_348_p2}, {2'd0}};

assign p_shl_fu_408_p3 = {{empty_4_fu_392_p2}, {2'd0}};

assign sext_ln19_fu_302_p0 = in_r;

assign sext_ln19_fu_302_p1 = sext_ln19_fu_302_p0;

assign sext_ln23_1_fu_310_p0 = shift_reg_2_i;

assign sext_ln23_1_fu_310_p1 = sext_ln23_1_fu_310_p0;

assign sext_ln23_2_fu_314_p0 = shift_reg_5_i;

assign sext_ln23_2_fu_314_p1 = sext_ln23_2_fu_314_p0;

assign sext_ln23_3_fu_326_p0 = shift_reg_10_i;

assign sext_ln23_3_fu_326_p1 = sext_ln23_3_fu_326_p0;

assign sext_ln23_4_fu_322_p0 = shift_reg_8_i;

assign sext_ln23_4_fu_322_p1 = sext_ln23_4_fu_322_p0;

assign sext_ln23_5_fu_440_p1 = $signed(add_ln23_2_fu_434_p2);

assign sext_ln23_fu_306_p0 = shift_reg_0_i;

assign sext_ln23_fu_306_p1 = sext_ln23_fu_306_p0;

assign shift_reg_0_o = in_r;

assign shift_reg_10_o = shift_reg_9_i;

assign shift_reg_11_o = shift_reg_10_i;

assign shift_reg_12_o = shift_reg_11_i;

assign shift_reg_13_load_cast_fu_330_p0 = shift_reg_13_i;

assign shift_reg_13_load_cast_fu_330_p1 = shift_reg_13_load_cast_fu_330_p0;

assign shift_reg_13_o = shift_reg_12_i;

assign shift_reg_14_o = shift_reg_13_i;

assign shift_reg_15 = shift_reg_14_read_reg_460;

assign shift_reg_1_o = shift_reg_0_i;

assign shift_reg_2_o = shift_reg_1_i;

assign shift_reg_3_o = shift_reg_2_i;

assign shift_reg_4_o = shift_reg_3_i;

assign shift_reg_5_o = shift_reg_4_i;

assign shift_reg_6_o = shift_reg_5_i;

assign shift_reg_7_load_cast_fu_318_p0 = shift_reg_7_i;

assign shift_reg_7_load_cast_fu_318_p1 = shift_reg_7_load_cast_fu_318_p0;

assign shift_reg_7_o = shift_reg_6_i;

assign shift_reg_8_o = shift_reg_7_i;

assign shift_reg_9_o = shift_reg_8_i;

assign tmp3_fu_340_p3 = {{tmp_fu_334_p2}, {1'd0}};

assign tmp4_cast_fu_360_p1 = $signed(tmp4_fu_354_p2);

assign tmp4_fu_354_p2 = ($signed(sext_ln23_1_fu_310_p1) + $signed(sext_ln23_3_fu_326_p1));

assign tmp5_fu_372_p2 = ($signed(tmp4_cast_fu_360_p1) - $signed(p_shl1_fu_364_p3));

assign tmp61_fu_378_p2 = (shift_reg_4_i + shift_reg_12_i);

assign tmp7_fu_384_p3 = {{tmp61_fu_378_p2}, {2'd0}};

assign tmp8_cast_fu_404_p1 = $signed(tmp8_fu_398_p2);

assign tmp8_fu_398_p2 = ($signed(sext_ln23_2_fu_314_p1) + $signed(shift_reg_13_load_cast_fu_330_p1));

assign tmp9_fu_422_p2 = ($signed(p_neg_fu_416_p2) - $signed(tmp8_cast_fu_404_p1));

assign tmp_fu_334_p2 = ($signed(sext_ln23_fu_306_p1) - $signed(sext_ln23_4_fu_322_p1));

endmodule //fir
